### ISSUE TITLE
Modificar txt expresiones regulares

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#12]
Explicar brevemente en qué consiste cada expresión regular de los códigos promocionales y poner uno o dos ejemplos de cada una

**Comment by julioom** [comment]
Prioridad: alta.    
Estado: finalizado.    
Descripción: Explicar brevemente en qué consiste cada expresión regular de los códigos promocionales y poner uno o dos ejemplos de cada una.

**Comment by javiparra17** [comment]
Usaremos la primera expresión regular
