### ISSUE TITLE
Hacer comprobaciones HTML5

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#15]
Hacer comprobaciones con HTML5 en el formulario. Las comprobaciones son:
- Campos NO vacíos: nombre, apellidos e email.
- El campo email cumpla la restricción y patrón de email
- En el caso de que haya un código promocional, que cumpla el patrón (^$)|(^[aA-zZ]{6}[0-9]{3}$)

**Comment by julioom** [comment]
Prioridad: alta.
Estado: en curso.
Descripción: Hacer comprobaciones con HTML5 en el formulario. Las comprobaciones son:

Campos NO vacíos: nombre, apellidos e email.
El campo email cumpla la restricción y patrón de email
En el caso de que haya un código promocional, que cumpla el patrón (^$)|(^[aA-zZ]{6}[0-9]{3}$)
