### ISSUE TITLE
Corrección de HTML

### ISSUE THREAD

**Issue by bernar95** [EGC-G2-Trabajo-1718/Registro#19]
Los valores de algunos de los parámetros de algunas de las etiquetas del formulario de registro están en español. Y tienen que estar en inglés.

**Comment by julioom** [comment]
Prioridad: urgente. 
Estado: en curso. 
Descripción: Los valores de algunos de los parámetros de algunas de las etiquetas del formulario de registro están en español. Y tienen que estar en inglés.
