### ISSUE TITLE
Creación de tests PHP

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#21]
Crear una carpeta con el nombre "tests" y dentro otra carpeta llamada "php". En esa última carpeta, añadir tests php

**Comment by julioom** [comment]
Prioridad: media.
Estado: en curso.
Descripción: Crear una carpeta con el nombre "tests" y dentro otra carpeta llamada "php". En esa última carpeta, añadir tests php.
