### ISSUE TITLE
Página de confirmación

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#23]
Después de introducir los datos en el formulario de registro y pulsar en registrar, tiene que redireccionarte a otra página en la que aparezca el total del precio del evento, y si hay un código promocional, que aparezca también el descuento. Abajo, dos botones, uno de Confirmar y otro de Cancelar. El botón Confirmar, acepta el cobro de dicha cantidad. (El cobro es simulado)

**Comment by julioom** [comment]
Prioridad: alta. 
Estado: en curso. 
Descripción: Después de introducir los datos en el formulario de registro y pulsar en registrar, tiene que redireccionarte a otra página en la que aparezca el total del precio del evento, y si hay un código promocional, que aparezca también el descuento. Abajo, dos botones, uno de Confirmar y otro de Cancelar. El botón Confirmar, acepta el cobro de dicha cantidad. (El cobro es simulado)
