### ISSUE TITLE
Confirmation form con errores

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#24]
Se han encontrado los siguientes errores a los que se le tienen que aplicar estas correcciones:
- Cambiar el nombre por confirmationForm.php
- Cambiar los mensajes y textos a español
- Unir el formulario con el formulario de confirmación
- Meter la información en un fieldset
- Cambiar el precio del evento por 890€
- Aplicar un descuento del 100% si hay código promocional y es correcto
- Añadir función al botón de Cancelar para volver al formulario de registro

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción: Se han encontrado los siguientes errores a los que se le tienen que aplicar estas correcciones:

-  Cambiar el nombre por confirmationForm.php
- Cambiar los mensajes y textos a español
- Unir el formulario con el formulario de confirmación
- Meter la información en un fieldset
- Cambiar el precio del evento por 890€
- Aplicar un descuento del 100% si hay código promocional y es correcto
- Añadir función al botón de Cancelar para volver al formulario de registro
