### ISSUE TITLE
Añadir campo de tarjeta de crédito

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#25]
En el formulario de confirmación, añadir un campo de Tarjeta de crédito, que tiene que ser obligatorio si no hay código de descuento.
Además, tiene que cumplir el patrón de tarjeta de crédito.

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción: En el formulario de confirmación, añadir un campo de Tarjeta de crédito, que tiene que ser obligatorio si no hay código de descuento.
Además, tiene que cumplir el patrón de tarjeta de crédito.

**Comment by javiparra17** [comment]
Añadir además:
Un campo cvv que solo admita 3 números
Un campo fecha de expiración: la cual tiene que ser posterior a la fecha actual

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción: En el formulario de confirmación, añadir un campo de Tarjeta de crédito, que tiene que ser obligatorio si no hay código de descuento.
Además, tiene que cumplir el patrón de tarjeta de crédito.
Añadir también:
Un campo cvv que solo admita 3 números
Un campo fecha de expiración: la cual tiene que ser posterior a la fecha actual
