### ISSUE TITLE
Añadir ID y fecha de registro

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#27]
Al registrarse un usuario, en la función de guardado en base de datos, hay que añadir lo siguiente:
- El campo ID: un identificador único del usuario registrado
- Fecha de registro: la fecha en la que se registra el usuario

**Comment by julioom** [comment]
Prioridad: alta.
Estado: en curso.
Descripción: Al registrarse un usuario, en la función de guardado en base de datos, hay que añadir lo siguiente:

- El campo ID: un identificador único del usuario registrado
- Fecha de registro: la fecha en la que se registra el usuario
