### ISSUE TITLE
Unir formulario con formulario de confirmación

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#28]
Al pulsar en "Registrar" en el formulario, debe redireccionarte al formulario de confirmación, llevando los datos del registro mediate POST.
Tras pulsar en Confirmar, se comprueba si hay tarjeta de crédito si no hay descuento, y si sigue el patrón de tarjeta de crédito. Si todo es correcto, al pulsar en Confirmar, se registra en la base de datos.
Crear las funciones que sean necesarias para esta funcionalidad

**Comment by julioom** [comment]
Prioridad: alta.
Estado: en curso.
Descripción: Al pulsar en "Registrar" en el formulario, debe redireccionarte al formulario de confirmación, llevando los datos del registro mediate POST.
Tras pulsar en Confirmar, se comprueba si hay tarjeta de crédito si no hay descuento, y si sigue el patrón de tarjeta de crédito. Si todo es correcto, al pulsar en Confirmar, se registra en la base de datos.
Crear las funciones que sean necesarias para esta funcionalidad
