### ISSUE TITLE
Creación de página de "Todo correcto"

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#29]
Si todo es correcto y el usuario se registra, tiene que redireccionarte a una página que indique al usuario que se ha registrado correctamente.
En dicha vista tiene que haber:
- Un mensaje que indique lo antes mencionado
- Un enlace "Volver" que redireccione al usuario de nuevo al formulario
El archivo debe llamarse successfulView.php

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción:Si todo es correcto y el usuario se registra, tiene que redireccionarte a una página que indique al usuario que se ha registrado correctamente.
En dicha vista tiene que haber:

- Un mensaje que indique lo antes mencionado
- Un enlace "Volver" que redireccione al usuario de nuevo al formulario
El archivo debe llamarse successfulView.php
