### ISSUE TITLE
Leer el codigo, apuntar cosas para cambiar y cosas que servirán y crear tareas

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#3]
Buscar en el código heredado ficheros y códigos que nos harán falta, y cosas que no

**Comment by julioom** [comment]
Prioridad alta

**Comment by julioom** [comment]
Prioridad: alta.
Estado: en curso.
Descripción: Buscar en el código heredado ficheros y códigos que nos harán falta, y cosas que no.
