### ISSUE TITLE
Cambio de codigo promocional a confirmationForm

### ISSUE THREAD

**Issue by rafgonvil** [EGC-G2-Trabajo-1718/Registro#32]
Cambio en el documento de registerForm borrando el codigo promocional y trasladandolo al documento de confirmationForm. 
Debe de modificarse el css para que coincida con con las dos vistas.

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción: Cambio en el documento de registerForm borrando el codigo promocional y trasladandolo al documento de confirmationForm.
Debe de modificarse el css para que coincida con con las dos vistas.
