### ISSUE TITLE
Corrección de confirmationForm.php

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#33]
Se han encontrado varios errores y los cambios a aplicar son los siguientes:
- Cambiar el type del input Tarjeta de crédito. Ahora es type="number" y debe ser type="text"
- Limitar el tamaño del input Tarjeta de crédito a 16 caracteres
- Limitar el tamaño del input Mes a 2 caracteres
- Limitar el tamaño del input Año a 4 caracteres
- Limitar el tamaño del input cvv a 3 caracteres
- Añadir un botón para aplicar el código promocional en lugar de usar "onmouseout"

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción: Se han encontrado varios errores y los cambios a aplicar son los siguientes:

- Cambiar el type del input Tarjeta de crédito. Ahora es type="number" y debe ser type="text"
- Limitar el tamaño del input Tarjeta de crédito a 16 caracteres
- Limitar el tamaño del input Mes a 2 caracteres
- Limitar el tamaño del input Año a 4 caracteres
- Limitar el tamaño del input cvv a 3 caracteres
- Añadir un botón para aplicar el código promocional en lugar de usar "onmouseout"
