### ISSUE TITLE
Diario de grupo (Tareas)

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#34]
Confeccionar para el diario del grupo una explicación y resumen de las tareas, indicando la fecha de inicio, responsable y fecha de fin. También incluir las issues de reporte de errores/bugs/fallos.

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción: Confeccionar para el diario del grupo una explicación y resumen de las tareas, indicando la fecha de inicio, responsable y fecha de fin. También incluir las issues de reporte de errores/bugs/fallos.
