### ISSUE TITLE
Diario de grupo (Reuniones) 

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#35]
Confeccionar para el diario del grupo un documento explicativo de las reuniones acontecidas, indicando la fecha y duración, y las decisiones tomadas

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: en curso.
Descripción: Confeccionar para el diario del grupo un documento explicativo de las reuniones acontecidas, indicando la fecha y duración, y las decisiones tomadas
