### ISSUE TITLE
Documento del proyecto

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#36]
Crear el documento del proyecto siguiendo las indicaciones del siguiente enlace:
https://github.com/EGCETSII/Entregables/wiki/Documento-del-proyecto

**Comment by julioom** [comment]
Prioridad: alta.
Estado: en curso.
Descripción: Crear el documento del proyecto siguiendo las indicaciones del siguiente enlace:
https://github.com/EGCETSII/Entregables/wiki/Documento-del-proyecto
