### ISSUE TITLE
Arreglar repositorio

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#40]
- Eliminar archivos innecesarios
- Trasladar los archivos buenos a la carpeta Trabajo
- Eliminar carpeta Trabajo2

**Comment by julioom** [comment]
Prioridad: Media.
Estado: en curso.
Descripción: 
- Eliminar archivos innecesarios
- Trasladar los archivos buenos a la carpeta Trabajo
- Eliminar carpeta Trabajo2
