### ISSUE TITLE
Modificar nombre de carpeta Trabajo

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#45]
Es necesario realizar dicho cambio de nombre para el despligue

**Comment by julioom** [comment]
Estado: en curso.
Prioridad: alta.
Descripción: Es necesario modificar el nombre de la carpeta Trabajo2 a Trabajo para el despliegue

**Comment by julioom** [comment]
Estado: en curso.
Prioridad: urgente.
Descripción: Es necesario modificar el nombre de la carpeta Trabajo2 a Trabajo para el despliegue
