### ISSUE TITLE
Modificar travis.yml

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#46]
Cambiar dos línes del fichero donde se hace referencia a la carpeta Trabajo2, y por lo mencionado en la issue #45, hay que cambiar dicha referencia por "Trabajo"

**Comment by julioom** [comment]
Estado: en curso.
Prioridad: urgente.
Descripción: Cambiar dos línes del fichero donde se hace referencia a la carpeta Trabajo2, y por lo mencionado en la issue #45, hay que cambiar dicha referencia por "Trabajo"
