### ISSUE TITLE
Corrección del formulario

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#7]
- Eliminar campo DNI
- Modificar el campo País para que sea un select
- Añadir campo Código promocional
- Cambiar el nombre del submit por "Registrarse"

Nota: en un futuro pueden añadirse más campos

**Comment by julioom** [comment]
Prioridad: urgente.
Estado: finalizado.
Descripción: Eliminar campo DNI. Modificar el campo País para que sea un select. Añadir campo Código promocional. Cambiar el nombre del submit por "Registrarse"
Nota: en un futuro pueden añadirse más campos
