### ISSUE TITLE
Modificar lugar del html y su nombre

### ISSUE THREAD

**Issue by javiparra17** [EGC-G2-Trabajo-1718/Registro#9]
Mover el archivo "Ejemplo.php" a la carpeta Trabajo, y eliminar la carpeta "EGC - Registro" y todo lo que contiene (carpeta ".settings" y archivo ".project")
Renombrar el archivo a "registerForm.php"

**Comment by julioom** [comment]
Prioridad: urgente. 
Estado: finalizado. 
Descripción: Mover el archivo "Ejemplo.php" a la carpeta Trabajo, y eliminar la carpeta "EGC - Registro" y todo lo que contiene (carpeta ".settings" y archivo ".project"). Renombrar el archivo a "registerForm.php"
